services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./src/database:/docker-entrypoint-initdb.d
    container_name: database

networks:
  default:
    name: nestjs-seed-network
